drop table IF EXISTS
    users,
    items,
    bookings,
    requests,
    comments;

create table users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE
);

create table requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR NOT NULL,
    requestor_id BIGINT NOT NULL,
    CONSTRAINT fk_requestor_user FOREIGN KEY (requestor_id)
    REFERENCES users (id) ON DELETE CASCADE
);

create table items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL,
    request_id BIGINT,
    CONSTRAINT fk_owner_user FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_item_request FOREIGN KEY (request_id)
    REFERENCES requests (id) ON DELETE CASCADE,
    CONSTRAINT UQ_OWNER_ITEM_NAME UNIQUE(owner_id, name)
);

create table bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id BIGINT NOT NULL,
    booker_id BIGINT NOT NULL,
    status VARCHAR NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_booking_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_booker_user FOREIGN KEY (booker_id)
    REFERENCES users (id) ON DELETE CASCADE
);

create table comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_comment_item FOREIGN KEY (item_id)
    REFERENCES items (id) ON DELETE CASCADE,
    CONSTRAINT fk_author_user FOREIGN KEY (author_id)
    REFERENCES users (id) ON DELETE CASCADE
);